#!/bin/bash

case "$1" in
    on)
	xrandr --output eDP1 --brightness 0.3
	xbacklight -set 1
	exit 0       
	;;
    off)
	xrandr --output eDP1 --brightness 1
	exit 0
	;;
    *)
	xrandr --output eDP1 --brightness `echo "scale=1; $1/10" | bc`
	xbacklight -set 1
	exit 0       
	;;
esac

exit 0
	  
	 
