#!/bin/bash

case "$1" in
    o)
	xrandr --output eDP-1 --brightness 1
	exit 0       
	;;
    off)
	xrandr --output eDP-1 --brightness 1
	exit 0
	;;
    *)
	xrandr --output eDP-1 --brightness `echo "scale=1; $1/10" | bc`
	xbacklight -set 1
	exit 0       
	;;
esac

exit 0
	  
	 
