#!/bin/bash

case "$1" in
    right)
	xrandr --output HDMI2 --right-of eDP1 --auto
	exit 0       
	;;
    left)
	xrandr --output HDMI2 --left-of eDP1 --auto
	exit 0
	;;
    off)
	xrandr --output HDMI2 --off
	exit 0       
	;;
    r)
	xrandr --output HDMI2 --right-of eDP1 --auto
	exit 0       
	;;
    l)
	xrandr --output HDMI2 --left-of eDP1 --auto
	exit 0
	;;
    o)
	xrandr --output HDMI2 --off
	exit 0       
	;;
    *)
	exit 1
	;;
esac

exit 0
	  
	 
